language: php
cache:
  bundler: true
  directories:
    - $HOME/tmp/drush
    - $HOME/.bundle
  apt: true

php:
  - 5.4
  - 5.5

notifications:
  email:
    - nick.veenhof@acquia.com

env:
  - PATH=$PATH:/home/travis/.composer/vendor/bin

# This will create the database
mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  - composer global require drush/drush:dev-master --prefer-source
  - cd /home/travis/.composer/vendor/drush/drush && composer require youngj/httpserver:dev-master#41dd2b7 && cd -
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

before_script:
  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  - git clone --depth 1 --branch 8.x http://git.drupal.org/project/drupal.git
  - cd drupal
  # Install the site
  - drush si standard --db-url=mysql://root:@localhost/drupal --yes
  - drush en --yes simpletest
  - drush cr
  - drush runserver --server=builtin 8080 &
  - sleep 4
  - phpenv rehash

script:
  # go to our Drupal directory
  - cd $TRAVIS_BUILD_DIR
  - git clone --depth 1 --branch 8.x http://git.drupal.org/project/drupal.git
  - cd $TRAVIS_BUILD_DIR/drupal
  - chmod go-w sites/default
  - cd $TRAVIS_BUILD_DIR/drupal/modules/
  - git clone --depth 1 --branch master https://github.com/nickveenhof/search-api-sandbox.git search_api
  - ls -la $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR/drupal
  - php core/scripts/run-tests.sh --verbose --module 'search_api' --color --concurrency 4 --php `which php` --url http://127.0.0.1:8080
