# Schema for the configuration files of the Search API module.

search_api.cron:
  type: mapping
  label: 'Search API cron settings'
  mapping:
    batch_count:
      type: integer
      label: 'Number of batches to create per cron run'
    worker_runtime:
      type: integer
      label: 'Maximum working time per cron batch'

search_api.index.*:
  type: mapping
  label: 'Search index'
  mapping:
    machine_name:
      type: string
      label: 'Machine name'
    name:
      type: label
      label: Name'
    uuid:
      type: string
      label: 'UUID'
    description:
      type: text
      label: 'Description'
    server:
      type: string
      label: 'Server'
    item_type:
      type: string
      label: 'Item type'
    langcode:
      type: string
      label: 'Language code'
    options:
      type: mapping
      label: 'Options'
      mapping:
        cron_limit:
          type: integer
          label: 'Cron batch size'
        index_directly:
          type: boolean
          label: 'Index items immediately'
        fields:
          type: sequence
          label: 'Fields'
          sequence:
            - type: mapping
              mapping:
                type:
                  type: string
                real_type:
                  type: string
                boost:
                  type: float
                entity_type:
                  type: string
        additional_fields:
          type: sequence
          label: 'Additional fields'
          sequence:
            - type: string
        processors:
          type: sequence
          label: 'Processors'
          sequence:
            - type: mapping
              mapping:
                status:
                  type: boolean
                weight:
                  type: integer
                settings:
                  type: mapping
    enabled:
      type: boolean
      label: 'Enabled'
    read_only:
      type: boolean
      label: 'Read-only'
