search_api.settings:
  type: mapping
  label: 'Search API settings'
  mapping:
    cron_worker_runtime:
      type: integer
      label: '@todo Is this used anywhere?'
    cron_limit:
      type: integer
      label: 'Cron batch size'
    default_tracker:
      type: string
      label: 'The default tracker plugin'
