# @todo Update the key when https://www.drupal.org/node/2291073 is fixed.
plugin.plugin_configuration.search_api_tracker.default:
  type: sequence
  label: 'Entity tracker configuration'
  sequence:
    type: string
    label: 'An entity bundle'
