search_api.index.*:
  type: config_entity
  label : 'Search index'
  mapping:
    id:
      type: string
      label: 'ID'
    name:
      type: label
      label: Name'
    uuid:
      type: string
      label: 'UUID'
    description:
      type: text
      label: 'Description'
    read_only:
      type: boolean
      label: 'Read-only'
    fields:
      type: sequence
      label: 'Indexed fields'
      sequence:
        type: mapping
        label: field
        mapping:
          label:
            type: string
            label: 'A label for the field'
          datasource_id:
            type: string
            label: 'The datasource ID of the field'
          property_path:
            type: string
            label: 'The property path of the field'
          type:
            type: string
            label: 'The data type of the field'
          boost:
            type: float
            label: 'The boost of the field'
          indexed_locked:
            type: boolean
            label: 'Whether the field is locked or can be removed'
          type_locked:
            type: boolean
            label: 'Whether the field''s data type is locked or can be changed'
          hidden:
            type: boolean
            label: 'Whether the field should appear in the UI'
    processors:
      type: sequence
      label: 'Processor settings'
      sequence:
        type: mapping
        label: 'A processor'
        mapping:
          processor_id:
            type: string
            label: 'The plugin ID of the processor'
          weights:
            type: sequence
            label: 'The processor''s weights for the different processing stages'
            sequence:
              type: integer
              label: 'The processor''s weight for this stage'
          settings:
            type: plugin.plugin_configuration.search_api_processor.[%parent.processor_id]
    options:
      type: mapping
      label: 'Options'
      mapping:
        cron_limit:
          type: integer
          label: 'Cron batch size'
        index_directly:
          type: boolean
          label: 'Index items immediately'
    datasources:
      type: sequence
      label: 'Datasource plugin IDs'
      sequence:
        type: string
    datasource_configs:
      type: sequence
      label: 'Datasource plugin configurations'
      sequence:
        type: search_api.datasource.plugin.[%key]
        label: 'Datasource plugin configuration'
    tracker:
      type: string
      label: 'Tracker plugin ID'
    tracker_config:
      label: 'Tracker config plugin'
      type: plugin.plugin_configuration.search_api_tracker.[%parent.tracker]
    server:
      type: string
      label: 'Server ID'
    status:
      type: boolean
      label: 'Status'
    langcode:
      type: string
      label: 'Language code'
    dependencies:
      type: config_dependencies
      label: 'Dependencies'
