views.query.search_api_query:
  type: views_query
  label: 'Search API query'
  mapping:
    search_api_bypass_access:
      type: boolean
      label: If the underlying search index has access checks enabled, this option allows you to disable them for this view.
    entity_access:
      type: boolean
      label: Execute an access check for all result entities.
    parse_mode:
      type: string
      label: Chooses how the search keys will be parsed.

views.row.search_api:
  type: views_row
  label: 'Search API rendered item'
  mapping:
    view_modes:
      type: sequence
      label: View modes for each datasource
      sequence:
        type: sequence
        label: A list of all the bundles and their configured view mode
        sequence:
          type: string
          label: View mode for the specific bundle

views.argument.search_api_more_like_this:
  type: views_argument
  label: 'Search API more like this'
  mapping:
    fields:
      type: sequence
      label: 'Fields'
      sequence:
        type: string
        label: 'Field'

views.filter.search_api_boolean:
  type: views.filter.boolean
  label: 'Search API boolean'

views.filter.search_api_datasource:
  type: views.filter.search_api_options
  label: 'Search API datasource'

views.filter.search_api_date:
  type: views.filter.date
  label: 'Search API date'

views.filter.search_api_fulltext:
  type: views_filter
  label: 'Search API fulltext search'
  mapping:
    min_length:
      type: integer
      label: Minimum search string length
    fields:
      type: sequence
      label: Fields to search on
      sequence:
        type: string
        label: Field name

views.filter.search_api_language:
  type: views.filter.search_api_options
  label: 'Search API language'

views.filter.search_api_numeric:
  type: views.filter.numeric
  label: 'Search API numeric'

views.filter.search_api_options:
  type: views.filter.many_to_one
  label: 'Search API options'

views.filter.search_api_string:
  type: views.filter.search_api_numeric
  label: 'Search API string'

views.filter.search_api_term:
  type: views.filter.taxonomy_index_tid
  label: 'Search API taxonomy term'

views.filter.search_api_text:
  type: views.filter.search_api_string
  label: 'Search API text'

views.filter.search_api_user:
  type: views.filter.user_name
  label: 'Search API user'

views.filter_value.search_api_boolean:
  type: boolean

views.filter_value.search_api_datasource:
  type: string

views.filter_value.search_api_date:
  type: string

views.filter_value.search_api_fulltext:
  type: string

views.filter_value.search_api_language:
  type: string

views.filter_value.search_api_numeric:
  type: views.filter_value.numeric

views.filter_value.search_api_options:
  type: sequence
  sequence:
    type: string
    label: 'Value'

views.filter_value.search_api_string:
  type: views.filter_value.numeric

views.filter_value.search_api_term:
  type: string

views.filter_value.search_api_text:
  type: string

views.filter_value.search_api_user:
  type: string

