machine_name: default_node_index
name: 'Default node index'
description: 'An automatically created search index for indexing node data. Might be configured to specific needs.'
server: ''
item_type: node
enabled: '0'
read_only: '0'
options:
  index_directly: '1'
  cron_limit: '50'
  data_alter_callbacks:
    search_api_alter_node_access:
      status: '1'
      weight: '0'
      settings: {  }
  processors:
    search_api_case_ignore:
      status: '1'
      weight: '0'
      settings:
        strings: '0'
    search_api_html_filter:
      status: '1'
      weight: '10'
      settings:
        title: '0'
        alt: '1'
        tags: "h1 = 5\nh2 = 3\nh3 = 2\nstrong = 2\nb = 2\nem = 1.5\nu = 1.5"
    search_api_tokenizer:
      status: '1'
      weight: '20'
      settings:
        spaces: '[^\p{L}\p{N}]'
        ignorable: '[-]'
  fields:
    type:
      type: string
    title:
      type: text
      boost: '5.0'
    promote:
      type: boolean
    sticky:
      type: boolean
    created:
      type: date
    changed:
      type: date
    author:
      type: integer
      entity_type: user
    comment_count:
      type: integer
    search_api_language:
      type: string
    'body:value':
      type: text
