machine_name: default_node_index
name: 'Default node index'
description: 'An automatically created search index for indexing node data. Might be configured to specific needs.'
readOnly: false
options:
  cron_limit: 50
  fields:
    'node:title':
      type: text
      boost: '5.0'
    'node:created':
      type: date
    'node:changed':
      type: date
    'node:promote':
      type: boolean
    'node:sticky':
      type: boolean
    'node:body':
      type: text
    'node:uid:user:uid':
      type: integer
  'additional fields':
    'node:uid': 1
  processors:
    search_api_stopwords_processor:
      status: 1
      weight: '0'
      settings:
        fields:
          'node:title': 'node:title'
          'node:body': 'node:body'
        file: ''
        stopwords: "but\r\ndid\r\nthe this that those\r\netc"
    search_api_tokenizer_processor:
      status: 1
      weight: '0'
      settings:
        fields:
          'node:title': 'node:title'
          'node:body': 'node:body'
        spaces: '[^[:alnum:]]'
        ignorable: '[''-]'
    search_api_html_filter_processor:
      status: 1
      weight: '0'
      settings:
        fields:
          'node:title': 'node:title'
          'node:body': 'node:body'
        title: 0
        alt: 1
        tags: "h1: 5\r\nh2: 3\r\nh3: 2\r\nstrong: 2\r\nb: 2\r\nem: 1.5\r\nu: 1.5"
datasourcePluginId: 'entity:node'
datasourcePluginConfig:
  default: '1'
  bundles: {  }
trackerPluginId: 'default_tracker'
trackerPluginConfig: {  }
serverMachineName: ''
status: true
